### ISSUE TITLE
Publish version 0.2.0 to dbt hub

### ISSUE THREAD

**Issue by sethwoodworth** [Montreal-Analytics/dbt-snowflake-utils#15]
The [dbt hub](https://hub.getdbt.com/montreal-analytics/snowflake_utils/latest/) for `snowflake_utils` lists `0.1.3` as the latest version although the repo has a release of `0.2.0`.

I'm not clear how the dbt hub is notified of new package releases @clrcrl

**Comment by MartinGuindon** [comment]
@sethwoodworth There's a process that runs, I believe, once every 24 hours. It probably just hasn't run yet.

**Comment by MartinGuindon** [comment]
The auto-generated PR is here: https://github.com/fishtown-analytics/hub.getdbt.com/pull/300

Just not sure if there's a manual process involved or not, but in any case it's out of my hands :)

**Comment by sethwoodworth** [comment]
Oh great! Thank you, I'll close the issue then

**Comment by clrcrl** [comment]
I have just been OOO for the last few days, hence the delay
