### ISSUE TITLE
Update dbt_utils package to reference dbt labs and not fishtown analytics 

### ISSUE THREAD

**Issue by amychen1776** [Montreal-Analytics/dbt-snowflake-utils#16]
With the rebranding, the Fishtown github org that was hosting the dbt utils package is now called dbt-labs 
![image](https://user-images.githubusercontent.com/46451573/125959724-000f7516-6d9e-49ec-bfd7-a3628510be21.png)

**Comment by JustMaris** [comment]
Created #17

**Comment by MartinGuindon** [comment]
Update done and release 0.3.0 issued.
