### ISSUE TITLE
[Bug] apply_meta_as_tags macro does not work with dbt<1.1.0

### ISSUE THREAD

**Issue by ogr003** [Montreal-Analytics/dbt-snowflake-utils#22]
# Current behavior
Due to https://github.com/dbt-labs/dbt-core/issues/4459, the `res.node.meta` node is not populated, meaning that no database tags are added by the `apply_meta_as_tags` macro.

# Expected behavior
Should identify all models that has populated the `database_tags` meta field.

# Environment
dbt: 1.0.1

# Additional context
The `res.node.config.meta` field looks to be populated in `dbt==1.0.1`, so a suggested approach could be to use this instead. Alternatively, the dbt version constraint could be updated to `dbt>=1.1.0`, when the issue was resolved.

**Comment by MartinGuindon** [comment]
@jamesweakley Do you want to take a look?

**Comment by jamesweakley** [comment]
@MartinGuindon yes I’ll take a look

**Comment by jamesweakley** [comment]
@ogr003 thanks for reporting the issue and also pointing out the solution!

I've opened a PR for this.

**Comment by MartinGuindon** [comment]
Fixed in release 0.4.1. Thanks @jamesweakley !
