### ISSUE TITLE
how to add Multiple Values to same Tag 

### ISSUE THREAD

**Issue by choudrybabu** [Montreal-Analytics/dbt-snowflake-utils#35]
i was trying to add multiple values to one Tag key 
ex: Region: APAC, LATAM, NA..
i have tried few ways and i am unable to see all those tag values in database , last one survives 

meta:
        database_tags:
          region: APAC
          region: LATAM
          region: NA

can you please let me know if this is a bug or am i doing something  wrong

**Comment by jamesweakley** [comment]
Hi @choudrybabu ,
Snowflake only supports assigning a single string value for each tag, so this isn't possible.

**Comment by choudrybabu** [comment]
yeah, thanks for the clarification , we can close this
