### ISSUE TITLE
YML Processing Errors in dbt v1.5 with dbt-snowflake-utils v0.6.0

### ISSUE THREAD

**Issue by abupp** [Montreal-Analytics/dbt-snowflake-utils#44]
Today, due to our dbt project configuration, we automatically switched from v0.5.0 to v0.6.0 when the latter was released. This resulted in a number of failed jobs that shared this error message:

`19:30:48  Encountered an error:
Parsing Error
  Error reading snowflake_utils: macros.yml - Runtime Error
    Syntax error near line 25
    ------------------------------
    22 |       - name: destination_database
    23 |         description: Destination database name, i.e. the new database to be created
    24 |       - name: new_owner_role
    25 |         description: [Optional] The new owner role of the newly created object
    26 | 
    27 |   - name: clone_schema
    28 |     arguments:
    
    Raw Error:
    ------------------------------
    while parsing a block mapping
      in "", line 24, column 9
    did not find expected key
      in "", line 25, column 33`

After reverting back to dbt-snowflake-utils v0.5.0 the problem went away.

**Comment by JFrackson** [comment]
This is now resolved in 0.6.1 and 0.6.0 has also been dropped to make sure nobody else hits the same issue.
