### ISSUE TITLE
Macro name wrong in doc

### ISSUE THREAD

**Issue by felipecoxanet** [Montreal-Analytics/dbt-snowflake-utils#52]
https://github.com/Montreal-Analytics/dbt-snowflake-utils/blob/73142f2731ceb87150906ebbf6a8d407f0365857/macros/macros.yml#L52

The macro name in DOC is `grant_ownershop_on_schema_objects`, but the rigth name is `grant_ownership_on_schema_objects`

**Comment by JFrackson** [comment]
Fixed with this commit: https://github.com/Montreal-Analytics/dbt-snowflake-utils/commit/3d72c298e5a18513aa3621f7107f28937e846769
