### ISSUE TITLE
Wrong patch for macro grant_ownership_on_schema_objects

### ISSUE THREAD

**Issue by markusyk-knowit** [Montreal-Analytics/dbt-snowflake-utils#53]
dbt reports 
_[WARNING]: Found patch for macro "grant_ownershop_on_schema_objects" which was not found_

This should be grant_ownership_on_schema_objects which exists. 

https://github.com/Montreal-Analytics/dbt-snowflake-utils/blame/73142f2731ceb87150906ebbf6a8d407f0365857/macros/macros.yml#L52

**Comment by markusyk-knowit** [comment]
Ahh, duplicate issue #52

**Comment by JFrackson** [comment]
Fixed with this commit: https://github.com/Montreal-Analytics/dbt-snowflake-utils/commit/3d72c298e5a18513aa3621f7107f28937e846769
