### ISSUE TITLE
Additional Parameter for Source & Target DB

### ISSUE THREAD

**Issue by ckaiser-graniterock** [Montreal-Analytics/dbt-snowflake-utils#8]
Would be great if you could add two parameters. One for Source_database and another for destination_database. 

Example would be a clone of ABC_RAW.DBO to ABC_CLONE.DBO. 

dbt run-operation clone_schema --args "{'source_database': 'abc_raw', 'source_schema': 'analytics', 'detination_database': 'abc_clone', 'destination_schema': 'analytics'}"

Thanks!

**Comment by MartinGuindon** [comment]
Thanks Cody, that's a great point. I'll try to get this done within the next few days.

**Comment by MartinGuindon** [comment]
Resolved in merged PR #10 by @jtalmi. I'll issue a new release soon.
